// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {time} from '../models';

export function AddSyncRule(arg1:main.SyncRule):Promise<void>;

export function CheckForUpdatesManually():Promise<void>;

export function ClearSyncHistory():Promise<void>;

export function ClearSyncLogs():Promise<void>;

export function CreateFolder(arg1:string,arg2:string):Promise<void>;

export function CreateMinioFolder(arg1:string):Promise<void>;

export function CreateSyncReport(arg1:main.SyncStatus):Promise<string>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteFileFromMinio(arg1:string):Promise<void>;

export function DeleteSyncReport(arg1:string):Promise<void>;

export function DisableSyncRule(arg1:string):Promise<void>;

export function DownloadFile(arg1:string):Promise<Array<number>>;

export function DownloadFileFromMinio(arg1:string):Promise<Array<number>>;

export function EnableSyncRule(arg1:string):Promise<void>;

export function ExportSyncConfig(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetConflictCount():Promise<number>;

export function GetConflictFiles():Promise<Array<main.ConflictFile>>;

export function GetCurrentUser():Promise<string>;

export function GetEnabledSyncRules():Promise<Array<main.SyncRule>>;

export function GetFilePreview(arg1:string):Promise<main.FilePreview>;

export function GetFileType(arg1:string):Promise<string>;

export function GetMinioConfig():Promise<main.MinioConfig>;

export function GetMinioFileInfo(arg1:string):Promise<main.MinioFileInfo>;

export function GetStoragePath():Promise<string>;

export function GetSyncHistory():Promise<Array<main.SyncHistoryEntry>>;

export function GetSyncHistoryStats():Promise<Record<string, any>>;

export function GetSyncInterval():Promise<time.Duration>;

export function GetSyncLogs():Promise<Array<main.SyncLogEntry>>;

export function GetSyncMode():Promise<string>;

export function GetSyncProgress():Promise<main.SyncProgress>;

export function GetSyncReports():Promise<Array<string>>;

export function GetSyncRuleByID(arg1:string):Promise<main.SyncRule>;

export function GetSyncRuleByName(arg1:string):Promise<main.SyncRule>;

export function GetSyncRules():Promise<Array<main.SyncRule>>;

export function GetSyncStats():Promise<Record<string, any>>;

export function GetSyncStatus():Promise<main.SyncStatus>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetTrayMenuItems():Promise<Array<main.TrayMenuItem>>;

export function Greet(arg1:string):Promise<string>;

export function HandleSyncError(arg1:Error,arg2:string,arg3:string):Promise<void>;

export function HandleTrayMenuClick(arg1:string):Promise<void>;

export function HasPendingConflicts():Promise<boolean>;

export function ImportSyncConfig(arg1:string):Promise<void>;

export function IsLocalFileNewer(arg1:string,arg2:string):Promise<boolean>;

export function IsLoggedIn():Promise<boolean>;

export function IsRemoteFileNewer(arg1:string,arg2:string):Promise<boolean>;

export function ListFiles(arg1:string):Promise<Array<main.FileInfo>>;

export function ListMinioBuckets():Promise<Array<string>>;

export function ListMinioFiles(arg1:string):Promise<Array<main.MinioFileInfo>>;

export function ListMinioFilesByBucket(arg1:string,arg2:string):Promise<Array<main.MinioFileInfo>>;

export function LoadSyncRules():Promise<void>;

export function LogSyncEvent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<main.AuthResponse>;

export function Logout():Promise<void>;

export function MinimizeToTray():Promise<void>;

export function MonitorSyncStatus():Promise<void>;

export function OpenFileInExplorer(arg1:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function OptimizeSyncPerformance():Promise<void>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function ReadSyncReport(arg1:string):Promise<string>;

export function Register(arg1:string,arg2:string):Promise<void>;

export function RemoveSyncRule(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function ResetSyncProgress():Promise<void>;

export function ResetSyncState():Promise<void>;

export function ResolveAllConflicts(arg1:string):Promise<void>;

export function ResolveConflict(arg1:string,arg2:string):Promise<void>;

export function RunSyncCommand():Promise<void>;

export function SaveConfig():Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:Array<number>):Promise<void>;

export function SaveSyncReport(arg1:main.SyncStatus):Promise<void>;

export function SaveSyncRules():Promise<void>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function SendSyncNotification(arg1:string,arg2:string):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetSyncInterval(arg1:number):Promise<void>;

export function SetSyncMode(arg1:string):Promise<void>;

export function ShowFromTray():Promise<void>;

export function StartSync():Promise<void>;

export function StopSync():Promise<void>;

export function TestMinioConnection(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ToggleSyncStatus():Promise<boolean>;

export function TriggerManualSync():Promise<void>;

export function UpdateMinioConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:boolean):Promise<void>;

export function UpdateSyncConfig(arg1:boolean,arg2:number,arg3:string,arg4:string):Promise<void>;

export function UpdateSyncProgress(arg1:main.SyncProgress):Promise<void>;

export function UpdateSyncRule(arg1:main.SyncRule):Promise<void>;

export function UploadDataToMinio(arg1:Array<number>,arg2:string):Promise<void>;

export function UploadFile(arg1:string,arg2:Array<number>,arg3:string):Promise<void>;

export function UploadFileString(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UploadFileToMinio(arg1:string,arg2:string):Promise<void>;

export function ValidateSyncRule(arg1:main.SyncRule):Promise<void>;
