// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdatesManually() {
  return window['go']['main']['App']['CheckForUpdatesManually']();
}

export function ConnectISCSITarget(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectISCSITarget'](arg1, arg2, arg3, arg4);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateMinioFolder(arg1) {
  return window['go']['main']['App']['CreateMinioFolder'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteFileFromMinio(arg1) {
  return window['go']['main']['App']['DeleteFileFromMinio'](arg1);
}

export function DisableISCSIInitiator() {
  return window['go']['main']['App']['DisableISCSIInitiator']();
}

export function DisconnectISCSITarget(arg1) {
  return window['go']['main']['App']['DisconnectISCSITarget'](arg1);
}

export function DiscoverISCSITargets(arg1, arg2) {
  return window['go']['main']['App']['DiscoverISCSITargets'](arg1, arg2);
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function DownloadFileFromMinio(arg1) {
  return window['go']['main']['App']['DownloadFileFromMinio'](arg1);
}

export function EnableISCSIInitiator() {
  return window['go']['main']['App']['EnableISCSIInitiator']();
}

export function FormatISCSIDisk(arg1, arg2) {
  return window['go']['main']['App']['FormatISCSIDisk'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDiscoveredTargets() {
  return window['go']['main']['App']['GetDiscoveredTargets']();
}

export function GetDiskUsage(arg1) {
  return window['go']['main']['App']['GetDiskUsage'](arg1);
}

export function GetFilePreview(arg1) {
  return window['go']['main']['App']['GetFilePreview'](arg1);
}

export function GetFileType(arg1) {
  return window['go']['main']['App']['GetFileType'](arg1);
}

export function GetISCSIConnectionByTarget(arg1) {
  return window['go']['main']['App']['GetISCSIConnectionByTarget'](arg1);
}

export function GetISCSIConnections() {
  return window['go']['main']['App']['GetISCSIConnections']();
}

export function GetISCSIDisks() {
  return window['go']['main']['App']['GetISCSIDisks']();
}

export function GetISCSIPerformanceStats() {
  return window['go']['main']['App']['GetISCSIPerformanceStats']();
}

export function GetInitiatorConfig() {
  return window['go']['main']['App']['GetInitiatorConfig']();
}

export function GetMinioConfig() {
  return window['go']['main']['App']['GetMinioConfig']();
}

export function GetStoragePath() {
  return window['go']['main']['App']['GetStoragePath']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTrayMenuItems() {
  return window['go']['main']['App']['GetTrayMenuItems']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleTrayMenuClick(arg1) {
  return window['go']['main']['App']['HandleTrayMenuClick'](arg1);
}

export function IsISCSIEnabled() {
  return window['go']['main']['App']['IsISCSIEnabled']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListMinioBuckets() {
  return window['go']['main']['App']['ListMinioBuckets']();
}

export function ListMinioFiles(arg1) {
  return window['go']['main']['App']['ListMinioFiles'](arg1);
}

export function ListMinioFilesByBucket(arg1, arg2) {
  return window['go']['main']['App']['ListMinioFilesByBucket'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function MountISCSIDisk(arg1, arg2, arg3) {
  return window['go']['main']['App']['MountISCSIDisk'](arg1, arg2, arg3);
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RefreshISCSIDisks() {
  return window['go']['main']['App']['RefreshISCSIDisks']();
}

export function RefreshISCSITargets() {
  return window['go']['main']['App']['RefreshISCSITargets']();
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}

export function SaveInitiatorConfig(arg1) {
  return window['go']['main']['App']['SaveInitiatorConfig'](arg1);
}

export function ScanISCSIDisks() {
  return window['go']['main']['App']['ScanISCSIDisks']();
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function ShowFromTray() {
  return window['go']['main']['App']['ShowFromTray']();
}

export function TestMinioConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestMinioConnection'](arg1, arg2, arg3, arg4);
}

export function ToggleSyncStatus() {
  return window['go']['main']['App']['ToggleSyncStatus']();
}

export function UnmountISCSIDisk(arg1) {
  return window['go']['main']['App']['UnmountISCSIDisk'](arg1);
}

export function UpdateConnectionStats(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateConnectionStats'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateMinioConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateMinioConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UploadDataToMinio(arg1, arg2) {
  return window['go']['main']['App']['UploadDataToMinio'](arg1, arg2);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function UploadFileString(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFileString'](arg1, arg2, arg3);
}

export function UploadFileToMinio(arg1, arg2) {
  return window['go']['main']['App']['UploadFileToMinio'](arg1, arg2);
}
