// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdatesManually():Promise<void>;

export function ConnectISCSITarget(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ISCSIConnection>;

export function CreateFolder(arg1:string,arg2:string):Promise<void>;

export function CreateMinioFolder(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteFileFromMinio(arg1:string):Promise<void>;

export function DisableISCSIInitiator():Promise<void>;

export function DisconnectISCSITarget(arg1:string):Promise<void>;

export function DiscoverISCSITargets(arg1:string,arg2:number):Promise<Array<main.ISCSIDiscoveredTarget>>;

export function DownloadFile(arg1:string):Promise<Array<number>>;

export function DownloadFileFromMinio(arg1:string):Promise<Array<number>>;

export function EnableISCSIInitiator():Promise<void>;

export function FormatISCSIDisk(arg1:string,arg2:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetCurrentUser():Promise<string>;

export function GetDiscoveredTargets():Promise<Array<main.ISCSIDiscoveredTarget>>;

export function GetDiskUsage(arg1:string):Promise<number>;

export function GetFilePreview(arg1:string):Promise<main.FilePreview>;

export function GetFileType(arg1:string):Promise<string>;

export function GetISCSIConnectionByTarget(arg1:string):Promise<main.ISCSIConnection>;

export function GetISCSIConnections():Promise<Array<main.ISCSIConnection>>;

export function GetISCSIDisks():Promise<Array<main.ISCSIDisk>>;

export function GetISCSIPerformanceStats():Promise<main.ISCSIPerformanceStats>;

export function GetInitiatorConfig():Promise<main.ISCSIInitiatorConfig>;

export function GetMinioConfig():Promise<main.MinioConfig>;

export function GetStoragePath():Promise<string>;

export function GetSyncStatus():Promise<Record<string, any>>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetTrayMenuItems():Promise<Array<main.TrayMenuItem>>;

export function Greet(arg1:string):Promise<string>;

export function HandleTrayMenuClick(arg1:string):Promise<void>;

export function IsISCSIEnabled():Promise<boolean>;

export function IsLoggedIn():Promise<boolean>;

export function ListFiles(arg1:string):Promise<Array<main.FileInfo>>;

export function ListMinioBuckets():Promise<Array<string>>;

export function ListMinioFiles(arg1:string):Promise<Array<main.MinioFileInfo>>;

export function ListMinioFilesByBucket(arg1:string,arg2:string):Promise<Array<main.MinioFileInfo>>;

export function Login(arg1:string,arg2:string):Promise<main.AuthResponse>;

export function Logout():Promise<void>;

export function MinimizeToTray():Promise<void>;

export function MountISCSIDisk(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenFileInExplorer(arg1:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function RefreshISCSIDisks():Promise<void>;

export function RefreshISCSITargets():Promise<void>;

export function Register(arg1:string,arg2:string):Promise<main.AuthResponse>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:Array<number>):Promise<void>;

export function SaveInitiatorConfig(arg1:main.ISCSIInitiatorConfig):Promise<void>;

export function ScanISCSIDisks():Promise<Array<main.ISCSIDisk>>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function ShowFromTray():Promise<void>;

export function TestMinioConnection(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ToggleSyncStatus():Promise<boolean>;

export function UnmountISCSIDisk(arg1:string):Promise<void>;

export function UpdateConnectionStats(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number):Promise<void>;

export function UpdateMinioConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:boolean):Promise<void>;

export function UploadDataToMinio(arg1:Array<number>,arg2:string):Promise<void>;

export function UploadFile(arg1:string,arg2:Array<number>,arg3:string):Promise<void>;

export function UploadFileString(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UploadFileToMinio(arg1:string,arg2:string):Promise<void>;
