// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSyncRule(arg1) {
  return window['go']['main']['App']['AddSyncRule'](arg1);
}

export function CheckForUpdatesManually() {
  return window['go']['main']['App']['CheckForUpdatesManually']();
}

export function ClearSyncHistory() {
  return window['go']['main']['App']['ClearSyncHistory']();
}

export function ClearSyncLogs() {
  return window['go']['main']['App']['ClearSyncLogs']();
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateMinioFolder(arg1) {
  return window['go']['main']['App']['CreateMinioFolder'](arg1);
}

export function CreateSyncReport(arg1) {
  return window['go']['main']['App']['CreateSyncReport'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteFileFromMinio(arg1) {
  return window['go']['main']['App']['DeleteFileFromMinio'](arg1);
}

export function DeleteSyncReport(arg1) {
  return window['go']['main']['App']['DeleteSyncReport'](arg1);
}

export function DisableSyncRule(arg1) {
  return window['go']['main']['App']['DisableSyncRule'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function DownloadFileFromMinio(arg1) {
  return window['go']['main']['App']['DownloadFileFromMinio'](arg1);
}

export function EnableSyncRule(arg1) {
  return window['go']['main']['App']['EnableSyncRule'](arg1);
}

export function ExportSyncConfig(arg1) {
  return window['go']['main']['App']['ExportSyncConfig'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConflictCount() {
  return window['go']['main']['App']['GetConflictCount']();
}

export function GetConflictFiles() {
  return window['go']['main']['App']['GetConflictFiles']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetEnabledSyncRules() {
  return window['go']['main']['App']['GetEnabledSyncRules']();
}

export function GetFilePreview(arg1) {
  return window['go']['main']['App']['GetFilePreview'](arg1);
}

export function GetFileType(arg1) {
  return window['go']['main']['App']['GetFileType'](arg1);
}

export function GetMinioConfig() {
  return window['go']['main']['App']['GetMinioConfig']();
}

export function GetMinioFileInfo(arg1) {
  return window['go']['main']['App']['GetMinioFileInfo'](arg1);
}

export function GetStoragePath() {
  return window['go']['main']['App']['GetStoragePath']();
}

export function GetSyncHistory() {
  return window['go']['main']['App']['GetSyncHistory']();
}

export function GetSyncHistoryStats() {
  return window['go']['main']['App']['GetSyncHistoryStats']();
}

export function GetSyncInterval() {
  return window['go']['main']['App']['GetSyncInterval']();
}

export function GetSyncLogs() {
  return window['go']['main']['App']['GetSyncLogs']();
}

export function GetSyncMode() {
  return window['go']['main']['App']['GetSyncMode']();
}

export function GetSyncProgress() {
  return window['go']['main']['App']['GetSyncProgress']();
}

export function GetSyncReports() {
  return window['go']['main']['App']['GetSyncReports']();
}

export function GetSyncRuleByID(arg1) {
  return window['go']['main']['App']['GetSyncRuleByID'](arg1);
}

export function GetSyncRuleByName(arg1) {
  return window['go']['main']['App']['GetSyncRuleByName'](arg1);
}

export function GetSyncRules() {
  return window['go']['main']['App']['GetSyncRules']();
}

export function GetSyncStats() {
  return window['go']['main']['App']['GetSyncStats']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTrayMenuItems() {
  return window['go']['main']['App']['GetTrayMenuItems']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleSyncError(arg1, arg2, arg3) {
  return window['go']['main']['App']['HandleSyncError'](arg1, arg2, arg3);
}

export function HandleTrayMenuClick(arg1) {
  return window['go']['main']['App']['HandleTrayMenuClick'](arg1);
}

export function HasPendingConflicts() {
  return window['go']['main']['App']['HasPendingConflicts']();
}

export function ImportSyncConfig(arg1) {
  return window['go']['main']['App']['ImportSyncConfig'](arg1);
}

export function IsLocalFileNewer(arg1, arg2) {
  return window['go']['main']['App']['IsLocalFileNewer'](arg1, arg2);
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function IsRemoteFileNewer(arg1, arg2) {
  return window['go']['main']['App']['IsRemoteFileNewer'](arg1, arg2);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListMinioBuckets() {
  return window['go']['main']['App']['ListMinioBuckets']();
}

export function ListMinioFiles(arg1) {
  return window['go']['main']['App']['ListMinioFiles'](arg1);
}

export function ListMinioFilesByBucket(arg1, arg2) {
  return window['go']['main']['App']['ListMinioFilesByBucket'](arg1, arg2);
}

export function LoadSyncRules() {
  return window['go']['main']['App']['LoadSyncRules']();
}

export function LogSyncEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogSyncEvent'](arg1, arg2, arg3);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function MonitorSyncStatus() {
  return window['go']['main']['App']['MonitorSyncStatus']();
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function OptimizeSyncPerformance() {
  return window['go']['main']['App']['OptimizeSyncPerformance']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadSyncReport(arg1) {
  return window['go']['main']['App']['ReadSyncReport'](arg1);
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function RemoveSyncRule(arg1) {
  return window['go']['main']['App']['RemoveSyncRule'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function ResetSyncProgress() {
  return window['go']['main']['App']['ResetSyncProgress']();
}

export function ResetSyncState() {
  return window['go']['main']['App']['ResetSyncState']();
}

export function ResolveAllConflicts(arg1) {
  return window['go']['main']['App']['ResolveAllConflicts'](arg1);
}

export function ResolveConflict(arg1, arg2) {
  return window['go']['main']['App']['ResolveConflict'](arg1, arg2);
}

export function RunSyncCommand() {
  return window['go']['main']['App']['RunSyncCommand']();
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}

export function SaveSyncReport(arg1) {
  return window['go']['main']['App']['SaveSyncReport'](arg1);
}

export function SaveSyncRules() {
  return window['go']['main']['App']['SaveSyncRules']();
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function SendSyncNotification(arg1, arg2) {
  return window['go']['main']['App']['SendSyncNotification'](arg1, arg2);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetSyncInterval(arg1) {
  return window['go']['main']['App']['SetSyncInterval'](arg1);
}

export function SetSyncMode(arg1) {
  return window['go']['main']['App']['SetSyncMode'](arg1);
}

export function ShowFromTray() {
  return window['go']['main']['App']['ShowFromTray']();
}

export function StartSync() {
  return window['go']['main']['App']['StartSync']();
}

export function StopSync() {
  return window['go']['main']['App']['StopSync']();
}

export function TestMinioConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestMinioConnection'](arg1, arg2, arg3, arg4);
}

export function ToggleSyncStatus() {
  return window['go']['main']['App']['ToggleSyncStatus']();
}

export function TriggerManualSync() {
  return window['go']['main']['App']['TriggerManualSync']();
}

export function UpdateMinioConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateMinioConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateSyncConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSyncConfig'](arg1, arg2, arg3, arg4);
}

export function UpdateSyncProgress(arg1) {
  return window['go']['main']['App']['UpdateSyncProgress'](arg1);
}

export function UpdateSyncRule(arg1) {
  return window['go']['main']['App']['UpdateSyncRule'](arg1);
}

export function UploadDataToMinio(arg1, arg2) {
  return window['go']['main']['App']['UploadDataToMinio'](arg1, arg2);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function UploadFileString(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFileString'](arg1, arg2, arg3);
}

export function UploadFileToMinio(arg1, arg2) {
  return window['go']['main']['App']['UploadFileToMinio'](arg1, arg2);
}

export function ValidateSyncRule(arg1) {
  return window['go']['main']['App']['ValidateSyncRule'](arg1);
}
